[tool.poetry]
name = "planarenvs"
version = "0.1.0"
description = "Lightweight open-ai gym environments for planar kinematic chains."
authors = ["Max Spahn <m.spahn@tudelft.nl>"]

[tool.poetry.dependencies]
python = "^3.6,<3.11"
gym = "^0.21.0"
numpy = "^1.5.1"
pyglet = "^1.5.21"
scipy = "^1.5"
casadi = "<=3.5.5"
forwardkinematics = "^0.5.0"
motion-planning-scenes = {version = "^0.1.0", optional = true}

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
scenes = ["motion-planning-scenes"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
